/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaapplication1_JavaApplication1 */

#ifndef _Included_javaapplication1_JavaApplication1
#define _Included_javaapplication1_JavaApplication1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaapplication1_JavaApplication1
 * Method:    hello
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javaapplication1_JavaApplication1_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
