/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class ntrusign_Ntrusign */

#ifndef _Included_ntrusign_Ntrusign
#define _Included_ntrusign_Ntrusign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ntrusign_Ntrusign
 * Method:    InitialKey
 * Signature: (Ljava/lang/String;)V
 */
void Initial(char *str);
/*
 * Class:     ntrusign_Ntrusign
 * Method:    Sign
 * Signature: ([B[B)[B
 */
char * Ntrusign(char *msg,char *sk);

/*
 * Class:     ntrusign_Ntrusign
 * Method:    Verify
 * Signature: ([B[B[B)Z
 */
char * GetPublicKey();

/*
 * Class:     ntrusign_Ntrusign
 * Method:    GetPrivateKey
 * Signature: ()[B
 */
char * GetPrivateKey();
/*
 * Class:     ntrusign_Ntrusign
 * Method:    GetPublicKey
 * Signature: ()[B
 */
int Ntrusign_Verify(char * msg,char *sm, char pk);

#ifdef __cplusplus
}
#endif
#endif
